version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 244466666
      MYSQL_DATABASE: postech
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3307:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/postech
      SPRING_DATASOURCE_USERNAME: usertc
      SPRING_DATASOURCE_PASSWORD: 244466666
